[package]
name = "nispor-clib"
description = "Nispor C binding"
version = "1.2.3"
authors = ["Gris Ge <fge@redhat.com>"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "nispor"
path = "lib.rs"
crate-type = ["cdylib"]
doc = false

[dependencies]
nispor = { path = "../lib", version="1.0" }
libc = "0.2.74"
serde_json = "1.0"
