[workspace]
resolver = "2"
members = [
    "src/lib",
    "src/cli",
]

[workspace.metadata.vendor-filter]
# For now we only care about tier 1+2 Linux
platforms = ["*-unknown-linux-gnu"]
tier = "2"
all-features = true

[workspace.package]
rust-version = "1.77"
version = "2.0.0"
authors = ["Gris Ge <fge@redhat.com>"]
description = "Unified interface for Linux network state querying"
edition = "2021"
license = "Apache-2.0"
documentation = "https://github.com/nispor/nispor"
homepage = "https://github.com/nispor/nispor"
repository = "https://github.com/nispor/nispor"
keywords = ["network"]
categories = ["network-programming", "os"]


[workspace.dependencies]
clap = { version = "4.2", features = ["cargo"] }
env_logger = "0.11.0"
ethtool = "0.2.8"
futures = "0.3.21"
libc = "0.2.155"
log = "0.4.17"
mptcp-pm = "0.1.4"
#rtnetlink = "0.19.0"
rtnetlink = { git = "https://github.com/rust-netlink/rtnetlink" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.9"
tokio = { version = "1.19.2", features = ["macros", "rt"] }
wl-nl80211 = "0.4.0"
